// Mocks generated by Mockito 5.4.5 from annotations
// in flutter_product_app_assesment/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:ui' as _i20;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dio/dio.dart' as _i3;
import 'package:flutter/material.dart' as _i9;
import 'package:flutter_product_app_assesment/core/errors/failures.dart'
    as _i12;
import 'package:flutter_product_app_assesment/core/network/api_client.dart'
    as _i14;
import 'package:flutter_product_app_assesment/core/network/network_info.dart'
    as _i17;
import 'package:flutter_product_app_assesment/data/datasources/db_service.dart'
    as _i15;
import 'package:flutter_product_app_assesment/data/models/product_model.dart'
    as _i16;
import 'package:flutter_product_app_assesment/domain/entities/product.dart'
    as _i13;
import 'package:flutter_product_app_assesment/domain/repositories/product_repository.dart'
    as _i10;
import 'package:flutter_product_app_assesment/domain/usecases/get_products.dart'
    as _i5;
import 'package:flutter_product_app_assesment/domain/usecases/search_products.dart'
    as _i6;
import 'package:flutter_product_app_assesment/domain/usecases/toggle_favorite.dart'
    as _i7;
import 'package:flutter_product_app_assesment/presentation/controllers/product_controller.dart'
    as _i18;
import 'package:get/get.dart' as _i8;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i19;
import 'package:hive_flutter/hive_flutter.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i21;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_1 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_2<T> extends _i1.SmartFake implements _i3.Response<T> {
  _FakeResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_3<E> extends _i1.SmartFake implements _i4.Box<E> {
  _FakeBox_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetProductsUseCase_4 extends _i1.SmartFake
    implements _i5.GetProductsUseCase {
  _FakeGetProductsUseCase_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchProductsUseCase_5 extends _i1.SmartFake
    implements _i6.SearchProductsUseCase {
  _FakeSearchProductsUseCase_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeToggleFavoriteUseCase_6 extends _i1.SmartFake
    implements _i7.ToggleFavoriteUseCase {
  _FakeToggleFavoriteUseCase_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRxList_7<E> extends _i1.SmartFake implements _i8.RxList<E> {
  _FakeRxList_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRxBool_8 extends _i1.SmartFake implements _i8.RxBool {
  _FakeRxBool_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRxString_9 extends _i1.SmartFake implements _i8.RxString {
  _FakeRxString_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScrollController_10 extends _i1.SmartFake
    implements _i9.ScrollController {
  _FakeScrollController_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextEditingController_11 extends _i1.SmartFake
    implements _i9.TextEditingController {
  _FakeTextEditingController_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternalFinalCallback_12<T> extends _i1.SmartFake
    implements _i8.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i10.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i2.Either<_i12.Failure, List<_i13.Product>>> getProducts(
    int? skip,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [
            skip,
            limit,
          ],
        ),
        returnValue:
            _i11.Future<_i2.Either<_i12.Failure, List<_i13.Product>>>.value(
                _FakeEither_0<_i12.Failure, List<_i13.Product>>(
          this,
          Invocation.method(
            #getProducts,
            [
              skip,
              limit,
            ],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, List<_i13.Product>>>);

  @override
  _i11.Future<_i2.Either<_i12.Failure, List<_i13.Product>>> searchProducts(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProducts,
          [query],
        ),
        returnValue:
            _i11.Future<_i2.Either<_i12.Failure, List<_i13.Product>>>.value(
                _FakeEither_0<_i12.Failure, List<_i13.Product>>(
          this,
          Invocation.method(
            #searchProducts,
            [query],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, List<_i13.Product>>>);

  @override
  _i11.Future<_i2.Either<_i12.Failure, List<_i13.Product>>> getFavorites() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue:
            _i11.Future<_i2.Either<_i12.Failure, List<_i13.Product>>>.value(
                _FakeEither_0<_i12.Failure, List<_i13.Product>>(
          this,
          Invocation.method(
            #getFavorites,
            [],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, List<_i13.Product>>>);

  @override
  _i11.Future<_i2.Either<_i12.Failure, void>> addToFavorites(
          _i13.Product? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [product],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, void>>.value(
            _FakeEither_0<_i12.Failure, void>(
          this,
          Invocation.method(
            #addToFavorites,
            [product],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, void>>);

  @override
  _i11.Future<_i2.Either<_i12.Failure, void>> removeFromFavorites(
          int? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [productId],
        ),
        returnValue: _i11.Future<_i2.Either<_i12.Failure, void>>.value(
            _FakeEither_0<_i12.Failure, void>(
          this,
          Invocation.method(
            #removeFromFavorites,
            [productId],
          ),
        )),
      ) as _i11.Future<_i2.Either<_i12.Failure, void>>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i14.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_1(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i3.Dio);

  @override
  _i11.Future<_i3.Response<dynamic>> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {#queryParameters: queryParameters},
        ),
        returnValue:
            _i11.Future<_i3.Response<dynamic>>.value(_FakeResponse_2<dynamic>(
          this,
          Invocation.method(
            #get,
            [path],
            {#queryParameters: queryParameters},
          ),
        )),
      ) as _i11.Future<_i3.Response<dynamic>>);
}

/// A class which mocks [DbService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDbService extends _i1.Mock implements _i15.DbService {
  MockDbService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Box<_i16.ProductModel> get productsBox => (super.noSuchMethod(
        Invocation.getter(#productsBox),
        returnValue: _FakeBox_3<_i16.ProductModel>(
          this,
          Invocation.getter(#productsBox),
        ),
      ) as _i4.Box<_i16.ProductModel>);

  @override
  _i4.Box<_i16.ProductModel> get favoritesBox => (super.noSuchMethod(
        Invocation.getter(#favoritesBox),
        returnValue: _FakeBox_3<_i16.ProductModel>(
          this,
          Invocation.getter(#favoritesBox),
        ),
      ) as _i4.Box<_i16.ProductModel>);

  @override
  _i4.Box<dynamic> get settingsBox => (super.noSuchMethod(
        Invocation.getter(#settingsBox),
        returnValue: _FakeBox_3<dynamic>(
          this,
          Invocation.getter(#settingsBox),
        ),
      ) as _i4.Box<dynamic>);

  @override
  _i11.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> saveSetting(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSetting,
          [
            key,
            value,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<String?> getSetting(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getSetting,
          [key],
        ),
        returnValue: _i11.Future<String?>.value(),
      ) as _i11.Future<String?>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i17.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i11.Future<bool>.value(false),
      ) as _i11.Future<bool>);
}

/// A class which mocks [ProductController].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductController extends _i1.Mock implements _i18.ProductController {
  MockProductController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.GetProductsUseCase get getProductsUseCase => (super.noSuchMethod(
        Invocation.getter(#getProductsUseCase),
        returnValue: _FakeGetProductsUseCase_4(
          this,
          Invocation.getter(#getProductsUseCase),
        ),
      ) as _i5.GetProductsUseCase);

  @override
  _i6.SearchProductsUseCase get searchProductsUseCase => (super.noSuchMethod(
        Invocation.getter(#searchProductsUseCase),
        returnValue: _FakeSearchProductsUseCase_5(
          this,
          Invocation.getter(#searchProductsUseCase),
        ),
      ) as _i6.SearchProductsUseCase);

  @override
  _i7.ToggleFavoriteUseCase get toggleFavoriteUseCase => (super.noSuchMethod(
        Invocation.getter(#toggleFavoriteUseCase),
        returnValue: _FakeToggleFavoriteUseCase_6(
          this,
          Invocation.getter(#toggleFavoriteUseCase),
        ),
      ) as _i7.ToggleFavoriteUseCase);

  @override
  _i8.RxList<_i13.Product> get products => (super.noSuchMethod(
        Invocation.getter(#products),
        returnValue: _FakeRxList_7<_i13.Product>(
          this,
          Invocation.getter(#products),
        ),
      ) as _i8.RxList<_i13.Product>);

  @override
  set products(_i8.RxList<_i13.Product>? _products) => super.noSuchMethod(
        Invocation.setter(
          #products,
          _products,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.RxBool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: _FakeRxBool_8(
          this,
          Invocation.getter(#isLoading),
        ),
      ) as _i8.RxBool);

  @override
  set isLoading(_i8.RxBool? _isLoading) => super.noSuchMethod(
        Invocation.setter(
          #isLoading,
          _isLoading,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.RxBool get isMoreLoading => (super.noSuchMethod(
        Invocation.getter(#isMoreLoading),
        returnValue: _FakeRxBool_8(
          this,
          Invocation.getter(#isMoreLoading),
        ),
      ) as _i8.RxBool);

  @override
  set isMoreLoading(_i8.RxBool? _isMoreLoading) => super.noSuchMethod(
        Invocation.setter(
          #isMoreLoading,
          _isMoreLoading,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.RxString get errorMessage => (super.noSuchMethod(
        Invocation.getter(#errorMessage),
        returnValue: _FakeRxString_9(
          this,
          Invocation.getter(#errorMessage),
        ),
      ) as _i8.RxString);

  @override
  set errorMessage(_i8.RxString? _errorMessage) => super.noSuchMethod(
        Invocation.setter(
          #errorMessage,
          _errorMessage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.RxBool get isSearching => (super.noSuchMethod(
        Invocation.getter(#isSearching),
        returnValue: _FakeRxBool_8(
          this,
          Invocation.getter(#isSearching),
        ),
      ) as _i8.RxBool);

  @override
  set isSearching(_i8.RxBool? _isSearching) => super.noSuchMethod(
        Invocation.setter(
          #isSearching,
          _isSearching,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get limit => (super.noSuchMethod(
        Invocation.getter(#limit),
        returnValue: 0,
      ) as int);

  @override
  int get skip => (super.noSuchMethod(
        Invocation.getter(#skip),
        returnValue: 0,
      ) as int);

  @override
  set skip(int? _skip) => super.noSuchMethod(
        Invocation.setter(
          #skip,
          _skip,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get canLoadMore => (super.noSuchMethod(
        Invocation.getter(#canLoadMore),
        returnValue: false,
      ) as bool);

  @override
  set canLoadMore(bool? _canLoadMore) => super.noSuchMethod(
        Invocation.setter(
          #canLoadMore,
          _canLoadMore,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.ScrollController get scrollController => (super.noSuchMethod(
        Invocation.getter(#scrollController),
        returnValue: _FakeScrollController_10(
          this,
          Invocation.getter(#scrollController),
        ),
      ) as _i9.ScrollController);

  @override
  _i9.TextEditingController get searchController => (super.noSuchMethod(
        Invocation.getter(#searchController),
        returnValue: _FakeTextEditingController_11(
          this,
          Invocation.getter(#searchController),
        ),
      ) as _i9.TextEditingController);

  @override
  _i8.RxString get searchText => (super.noSuchMethod(
        Invocation.getter(#searchText),
        returnValue: _FakeRxString_9(
          this,
          Invocation.getter(#searchText),
        ),
      ) as _i8.RxString);

  @override
  set searchText(_i8.RxString? _searchText) => super.noSuchMethod(
        Invocation.setter(
          #searchText,
          _searchText,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_12<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i8.InternalFinalCallback<void>);

  @override
  _i8.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_12<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i8.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
      ) as int);

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onSearchChanged(String? value) => super.noSuchMethod(
        Invocation.method(
          #onSearchChanged,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> fetchProducts({bool? isRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchProducts,
          [],
          {#isRefresh: isRefresh},
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> loadMoreProducts() => (super.noSuchMethod(
        Invocation.method(
          #loadMoreProducts,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> search(String? query) => (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> toggleFavorite(_i13.Product? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [product],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Disposer addListener(_i19.GetStateUpdate? listener) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
      ) as _i19.Disposer);

  @override
  void removeListener(_i20.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListenerId(
    Object? id,
    _i20.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i19.Disposer addListenerId(
    Object? key,
    _i19.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
      ) as _i19.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBox<E> extends _i1.Mock implements _i4.Box<E> {
  MockBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<E> get values => (super.noSuchMethod(
        Invocation.getter(#values),
        returnValue: <E>[],
      ) as Iterable<E>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i21.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  bool get isOpen => (super.noSuchMethod(
        Invocation.getter(#isOpen),
        returnValue: false,
      ) as bool);

  @override
  bool get lazy => (super.noSuchMethod(
        Invocation.getter(#lazy),
        returnValue: false,
      ) as bool);

  @override
  Iterable<dynamic> get keys => (super.noSuchMethod(
        Invocation.getter(#keys),
        returnValue: <dynamic>[],
      ) as Iterable<dynamic>);

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
      ) as int);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
      ) as bool);

  @override
  bool get isNotEmpty => (super.noSuchMethod(
        Invocation.getter(#isNotEmpty),
        returnValue: false,
      ) as bool);

  @override
  Iterable<E> valuesBetween({
    dynamic startKey,
    dynamic endKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #valuesBetween,
          [],
          {
            #startKey: startKey,
            #endKey: endKey,
          },
        ),
        returnValue: <E>[],
      ) as Iterable<E>);

  @override
  E? getAt(int? index) => (super.noSuchMethod(Invocation.method(
        #getAt,
        [index],
      )) as E?);

  @override
  Map<dynamic, E> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <dynamic, E>{},
      ) as Map<dynamic, E>);

  @override
  dynamic keyAt(int? index) => super.noSuchMethod(Invocation.method(
        #keyAt,
        [index],
      ));

  @override
  _i11.Stream<_i4.BoxEvent> watch({dynamic key}) => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
          {#key: key},
        ),
        returnValue: _i11.Stream<_i4.BoxEvent>.empty(),
      ) as _i11.Stream<_i4.BoxEvent>);

  @override
  bool containsKey(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i11.Future<void> put(
    dynamic key,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> putAt(
    int? index,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAt,
          [
            index,
            value,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> putAll(Map<dynamic, E>? entries) => (super.noSuchMethod(
        Invocation.method(
          #putAll,
          [entries],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<int> add(E? value) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [value],
        ),
        returnValue: _i11.Future<int>.value(0),
      ) as _i11.Future<int>);

  @override
  _i11.Future<Iterable<int>> addAll(Iterable<E>? values) => (super.noSuchMethod(
        Invocation.method(
          #addAll,
          [values],
        ),
        returnValue: _i11.Future<Iterable<int>>.value(<int>[]),
      ) as _i11.Future<Iterable<int>>);

  @override
  _i11.Future<void> delete(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> deleteAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteAt,
          [index],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> deleteAll(Iterable<dynamic>? keys) => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [keys],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> compact() => (super.noSuchMethod(
        Invocation.method(
          #compact,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i11.Future<int>.value(0),
      ) as _i11.Future<int>);

  @override
  _i11.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> deleteFromDisk() => (super.noSuchMethod(
        Invocation.method(
          #deleteFromDisk,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> flush() => (super.noSuchMethod(
        Invocation.method(
          #flush,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}
